### PR TITLE
Added WSS support to run_chat_server using Python ssl module

### PR DESCRIPTION
**Pull request by zsmith3**
- Used Python's built-in ssl module to add running a WSS server (instead of WS) as a command-line option on run_chat_server (both versions)
- Modified README.rst with this change
- Made a few other minor changes to pass some flake8 tests
- Added to .gitignore some files which seem to be generated on my (windows) setup

I tried running tests but some of them seemed to fail based on files I hadn't touched. Not used to Github/etc. so let me know if I've done anything wrong.

### CODE REVIEW

**Comment by delneg** [comment]
Thanks a lot for that.
Will review in a couple hours

**Review by delneg — APPROVED** [review]
Looks good to me.

**Comment by delneg** [comment]
Will also need to bump version & upload to pypi

**Comment by delneg** [comment]
Merged & released to pypi, version 0.1.9

**Comment by ledzgio** [comment]
I am having issues in production where I am running nginx on HTTPS and uwsgi deployed on an EC2 instance.

Here are my settings:
CHAT_WS_SERVER_HOST = 'ec2-***' # here I am using EC2 Public IPv4 DNS
CHAT_WS_SERVER_PORT = 5002
CHAT_WS_SERVER_PROTOCOL = 'wss'

I run the server as following:
python manage.py run_chat_server

In the browser console I get this error:
WebSocket connection to 'wss://ec2-***:5002/session_id/username' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR

And in the server console I get:

`07.10.20 16:58:49:DEBUG:Invalid handshake
Traceback (most recent call last):
  File "/home/admin/poc_platform/env/lib/python3.7/site-packages/websockets/http.py", line 96, in read_request
    request_line = await read_line(stream)
  File "/home/admin/poc_platform/env/lib/python3.7/site-packages/websockets/http.py", line 219, in read_line
    raise EOFError("line without CRLF")
EOFError: line without CRLF
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admin/poc_platform/env/lib/python3.7/site-packages/websockets/server.py", line 233, in read_http_request
    path, headers = await read_request(self.reader)
  File "/home/admin/poc_platform/env/lib/python3.7/site-packages/websockets/http.py", line 98, in read_request
    raise EOFError("connection closed while reading HTTP request line") from exc
EOFError: connection closed while reading HTTP request line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admin/poc_platform/env/lib/python3.7/site-packages/websockets/server.py", line 134, in handler
    extra_headers=self.extra_headers,
  File "/home/admin/poc_platform/env/lib/python3.7/site-packages/websockets/server.py", line 526, in handshake
    path, request_headers = await self.read_http_request()
  File "/home/admin/poc_platform/env/lib/python3.7/site-packages/websockets/server.py", line 235, in read_http_request
    raise InvalidMessage("did not receive a valid HTTP request") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP request
07.10.20 16:58:49:DEBUG:server > HTTP/1.1 400 Bad Request
`

Any idea?
thanks

**Pull request merged**
